language: generic

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  # install cmake 3.14.1.
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.14.1/cmake-3.14.1-Linux-x86_64.tar.gz
  - tar -xvf cmake-3.14.1-Linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.14.1-Linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  # install python packages.
  - pip install --upgrade pip && pip install -r requirements.txt

before_script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -Denable_test=ON
  - make sdist_install

script:
  - ctest -V
