language: generic

services: docker

before_install:
  - docker build -t sauci/cantp .

script:
  - docker run -v $(pwd):/usr/project sauci/cantp /bin/sh -c "mkdir build;cd build;cmake ..;make all;ctest -V;make gcov.info"

after_success:
  - bash <(curl -s https://codecov.io/bash) -s build
