language: generic

services: docker

before_install:
  - docker build -t sauci/cantp .

script:
  - mkdir docker_build
  - docker run -v $(pwd):/usr/project sauci/cantp /bin/sh -c "cd docker_build;cmake ..;make all;ctest -V"

after_success:
  - bash <(curl -s https://codecov.io/bash -s docker_build)
