language: generic

services: docker

before_install:
  - docker build --build-arg branch=$TRAVIS_BRANCH -t sauci/cantp .

script:
  - docker run sauci/cantp /bin/sh -c "cd docker_build;make all test CTEST_OUTPUT_ON_FAILURE=TRUE"
